Repository jenkins-x/jx3-versions, pull requests merged in 2020-09, with the labels that each got.

#1248 fix: use secret data keys in schema
  charts/jenkins-x/bucketrepo/secret-schema.yaml
  charts/jenkins-x/chartmuseum/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/lighthouse/secret-schema.yaml
  charts/jenkins-x/tekton/secret-schema.yaml
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job.yaml
  jenkins-x-gke.yml
  jenkins-x-terraform.yml
  jenkins-x-tls.yml
  src/Makefile.mk
Labels: approved, size/M

#1249 fix: upgrade jxboot helmfile resources version
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
Labels: size/S

#1251 fix: upgrade tekton
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/tekton/defaults.yaml
  charts/jenkins-x/tekton/secret-schema.yaml
  jenkins-x-gke-ghe.yml
  jx/bdd/ci.sh
  jx/bdd/ghe/README.md
  jx/bdd/ghe/ci.sh
Labels: size/M

#1258 fix: first spike of slack app
  charts/jx3/slack/defaults.yaml
  charts/jx3/slack/secret-schema.yaml
  jenkins-x-ghe.yml
  jx/bdd/ci.sh
  jx/bdd/ghe/ci.sh
Labels: size/S

#1262 fix: use URL for docker config.json
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  docker/gcr.io/jenkinsxio/builder-asciidoctor.yml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-dotnet.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs12x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-php5x.yml
  docker/gcr.io/jenkinsxio/builder-php7x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job.yaml
  jenkins-x-boot-helm3-mc.yml
  jenkins-x-boot-helm3.yml
  jenkins-x-default.yml
  jenkins-x-ghe.yml
  jenkins-x-gke.yml
  jenkins-x-gsm.yml
  jenkins-x-istio-tls.yml
  jenkins-x-istio.yml
  jenkins-x-kube.yml
  jenkins-x-mc.yml
  jenkins-x-remote.yml
  jenkins-x-storage.yml
  jenkins-x-terraform.yml
  jenkins-x-tls.yml
  jenkins-x-vault.yml
  jenkins-x.yml
  jx/bdd/ci.sh
  jx/bdd/ghe/ci.sh
  tests/go.sum
Labels: size/L

#1274 fix: avoid errors if no pipeline user defined in requirements
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: size/XS

#1267 fix(charts/bucketrepo): use storage repository URL from jx-requirements if available
  charts/jenkins-x/bucketrepo/secret-schema.yaml
Labels: ok-to-test, size/XS

#1281 fix: upgrade kaniko
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  docker/gcr.io/kaniko-project/executor.yml
Labels: size/XS

#1288 fix: upgrade to latest tekton
  charts/jenkins-x/tekton/defaults.yaml
  charts/jenkins-x/tekton/secret-schema.yaml
  charts/jenkins-x/tekton/values.yaml.gotmpl
  src/fake-secrets.yaml.gotmpl
Labels: size/M

#1296 fix: upgrade tekton and fix eks secret schema
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/tekton/defaults.yaml
  tests/go.sum
  tests/secret_schema_test.go
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-aks.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-aws.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-eks.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-gke.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-minikube.json
  tests/test_data/expected/jenkins-maven-settings/settings.xml/bucketrepo.xml
  tests/test_data/expected/jenkins-maven-settings/settings.xml/nexus.xml
  tests/test_data/expected/jenkins-maven-settings/settings.xml/none.xml
Labels: size/M

#1298 fix: for EKS
  charts/jenkins-x/tekton/secret-schema.yaml
Labels: size/XS

#1309 chore: let's add all so we include files that fall under hidden folde…
  src/Makefile.mk
Labels: size/XS

#1319 fix: avoid template errors if no clusterName
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: size/XS

#1321 fix: ugprade kubernetes external secrets
  charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  src/Makefile.mk
Labels: size/XS

#1332 chore: add jx-cli to version stream
  packages/jx-cli.yml
Labels: size/XS

#1343 fix: add kube BDD test
  jenkins-x-boot-helm3-mc.yml
  jenkins-x-boot-helm3.yml
  jenkins-x-default.yml
  jenkins-x-gsm.yml
  jenkins-x-istio-tls.yml
  jenkins-x-istio.yml
  jenkins-x-kube.yml
  jenkins-x-mc.yml
  jenkins-x-storage.yml
  jenkins-x-vault.yml
  jx/bdd/ci.sh
  jx/bdd/kube/ci.sh
  src/Makefile.mk
Labels: size/L

#1345 chore: lets switch to the jx namespace when performing verify steps after install
  packages/jx-cli.yml
  src/Makefile.mk
Labels: size/S

#1352 fix: remove old cruft
  kubeProviders/README.md
  kubeProviders/aks/README.md
  kubeProviders/aks/values.yaml.gotmpl
  kubeProviders/alibaba/README.md
  kubeProviders/alibaba/values.yaml.gotmpl
  kubeProviders/aws/README.md
  kubeProviders/aws/values.yaml.gotmpl
  kubeProviders/eks/README.md
  kubeProviders/eks/templates/irsa.yaml.gotmpl
  kubeProviders/eks/templates/jenkinsx-policies.yml
  kubeProviders/eks/templates/vault_cf_tmpl.yml
  kubeProviders/eks/values.yaml.gotmpl
  kubeProviders/gke/README.md
  kubeProviders/gke/values.yaml.gotmpl
  kubeProviders/icp/README.md
  kubeProviders/icp/values.yaml.gotmpl
  kubeProviders/iks/README.md
  kubeProviders/iks/values.yaml.gotmpl
  kubeProviders/oke/README.md
  kubeProviders/oke/values.yaml.gotmpl
  kubeProviders/openshift/values.yaml.gotmpl
  kubeProviders/pks/README.md
  kubeProviders/pks/values.yaml.gotmpl
Labels: size/XL

#1398 wip: feat: lets enable multi repo infra + cluster terraform BDD tests
  .gitignore
  jenkins-x-gke.yml
  jenkins-x-gsm.yml
  jx/bdd/ci.sh
  jx/bdd/gke/README.md
  jx/bdd/gke/ci.sh
  jx/bdd/gsm/ci.sh
  jx/bdd/vault/ci.sh
  jx/scripts/promote-vs.sh
  jx/scripts/recreate-vs.sh
Labels: do-not-merge/work-in-progress, size/L

#1402 chore: lets cleanup secrets created as part of the GSM BDD test
  jx/bdd/gsm/ci.sh
Labels: size/XS

#1407 chore: lets use a specific clean terraform ci script and gc cloud resources properly
  jenkins-x-gsm.yml
  jenkins-x-vault.yml
  jx/bdd/ci.sh
  jx/bdd/gsm/ci.sh
  jx/bdd/terraform-ci.sh
  jx/bdd/vault/ci.sh
Labels: approved, lgtm, size/L

#1428 fix: lets add a default label
  schedulers/default.yaml
Labels: size/XS

#1436 fix: better image for controller build
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  schedulers/environment.yaml
  schedulers/jx-meta-pipeline.yaml
  src/Makefile.mk
Labels: size/S

#1437 fix: use correct SA name for controller build
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  jx/bdd/terraform-ci.sh
Labels: approved, lgtm, size/XS

#1441 fix: upgrade jxboot-helmfile-resources
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS

#1449 chore: add jx-cli chart
  charts/jx3/jx-cli/defaults.yaml
Labels: approved, lgtm, size/XS

#1451 chore: replace with official kuberhealthy chart repo
  charts/kuberhealthy/kuberhealthy/defaults.yaml
  charts/repositories.yml
  charts/stable/kuberhealthy/values.yaml.gotmpl
Labels: approved, lgtm, size/XS

#1452 fix: upgrade jxboot-helmfile-resources chart
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  jenkins/README.md
  jenkins/job-templates/default.xml.gotmpl
  schedulers/jx-meta-pipeline.yaml
Labels: size/XL
