Repository jenkins-x/jx3-versions, pull requests merged in 2020-10, with the labels that each got.

#1464 fix: avoid breaking EKS
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
Labels: approved, size/XS

#1457 fix: upgrade versions and configuration for tekton engine
  charts/cdf/tekton-pipeline/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job.yaml
  jenkins-x-boot-helm3-mc.yml
  jenkins-x-boot-helm3.yml
  jenkins-x-default.yml
  jenkins-x-ghe.yml
  jenkins-x-gsm.yml
  jenkins-x-istio-tls.yml
  jenkins-x-istio.yml
  jenkins-x-kube.yml
  jenkins-x-mc.yml
  jenkins-x-storage.yml
  jenkins-x-terraform.yml
  jenkins-x-tls.yml
  jenkins-x-vault.yml
  jx/bdd/gsm/ci.sh
  packages/jx-cli.yml
  schedulers/default.yaml
  schedulers/environment.yaml
  schedulers/in-repo.yaml
  schedulers/jx-meta-pipeline.yaml
  src/Makefile.mk
Labels: size/L

#1492 fix: add support for the main branch
  schedulers/default.yaml
  schedulers/environment.yaml
  schedulers/jx-meta-pipeline.yaml
Labels: approved, size/XS

#1498 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#1501 fix: use v3 of build controller
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  schedulers/jx-meta-pipeline.yaml
Labels: size/S

#1505 fix: add jx-basic-auth support
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  schedulers/default.yaml
  schedulers/environment.yaml
  schedulers/in-repo.yaml
  schedulers/jx-meta-pipeline.yaml
Labels: size/M

#1508 fix: for maven security secret
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
Labels: approved, size/XS

#1513 fix: configure jx-pipeline-visualizer with lighthouse
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, size/S

#1514 chore: docs
  README.md
Labels: size/XS

#1522 fix: upgrade jx and build controller
  charts/cdf/tekton-pipeline/secret-schema.yaml
  charts/jenkins-x/bucketrepo/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  git-operator/job.yaml
  jenkins-x-boot-helm3-mc.yml
  jenkins-x-boot-helm3.yml
  jenkins-x-default.yml
  jenkins-x-ghe.yml
  jenkins-x-gsm.yml
  jenkins-x-istio-tls.yml
  jenkins-x-istio.yml
  jenkins-x-kube.yml
  jenkins-x-mc.yml
  jenkins-x-storage.yml
  jenkins-x-terraform.yml
  jenkins-x-tls.yml
  jenkins-x-vault.yml
  jx/bdd/ci.sh
  src/Makefile.mk
Labels: size/M

#1531 feat: modified docker helper for ACR for jxboot-helmfile-resources
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
Labels: needs-ok-to-test, size/S

#1541 feat: modified acr helper for tekton registry auth
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
Labels: needs-ok-to-test, size/XS

#1543 fix: upgrade to latest lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: size/XS

#1548 fix: upgrade lighthouse
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/defaults.yaml
  src/Makefile.mk
Labels: approved, size/XS

#1550 fix: use the correct workload identity SA for the UI
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: size/XS

#1557 chore: add new jx health check chart + kuberhealthy defaults
  charts/jx3/jx-kh-check/values.yaml.gotmpl
  charts/kuberhealthy/kuberhealthy/values.yaml.gotmpl
Labels: approved, size/S

#1560 chore: split kh check default versions into different helm releases so we can install into multiple namepsaces with different values
  charts/jx3/health-checks-install/defaults.yaml
  charts/jx3/health-checks-install/values.yaml.gotmpl
  charts/jx3/health-checks-jx/defaults.yaml
  charts/jx3/health-checks-jx/values.yaml.gotmpl
  charts/jx3/jx-kh-check/defaults.yaml
  charts/jx3/jx-kh-check/values.yaml copy.gotmpl
Labels: approved, size/M

#1565 chore: default kuberhealthy to the kuberhealthy namespace
  charts/kuberhealthy/kuberhealthy/defaults.yaml
Labels: approved, size/XS

#1566 fix: kuberhealthy check defaults
  charts/jx3/jx-kh-check/values.yaml copy.gotmpl
  charts/jx3/jx-kh-check/values.yaml.gotmpl
Labels: approved, size/M

#1586 fix: lets pin the jx-preview version for now
  charts/jx3/jx-preview/defaults.yaml
Labels: approved, size/XS

#1587 fix: upgrade to the latest jxboot-helmfile and tekton
  charts/cdf/tekton-pipeline/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS

#1570 fix: tekton use gitUrl from jxRequirements
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
Labels: do-not-merge/hold, needs-ok-to-test, size/XS

#1590 feat: added in azure external dns secret to chart values
  charts/bitnami/external-dns/values.yaml.gotmpl
Labels: needs-ok-to-test, size/XS

#1588 fix: lock down jx-pipelines-visualizer & jx-kh-check versions
  charts/jx3/health-checks-install/defaults.yaml
  charts/jx3/health-checks-jx/defaults.yaml
  charts/jx3/jx-kh-check/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, ok-to-test, size/XS

#1594 fix: better meta pipeline + LH main branch fix
  schedulers/jx-meta-pipeline.yaml
  src/base/namespaces/jx/lighthouse-config/jx-meta-pipeline.yaml
Labels: size/XL

#1603 fix: use latest build controller
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: size/XS

#1607 fix: switch to using jx-git-operator namespace
  .lighthouse/jenkins-x/bdd/ci.sh
  .lighthouse/jenkins-x/triggers.yaml
  charts/cdf/tekton-pipeline/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jenkins-x/tekton/secret-schema.yaml
  git-operator/resources/clusterrolebinding.yaml
  git-operator/resources/sa.yaml
Labels: size/M

#1616 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#1622 chore: lets auto upgrade our own infra
  .lighthouse/jenkins-x/release/promote-vs.sh
Labels: approved, size/S

#1623 fix: upgrade jx-cli and jx-preview
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/release/promote-vs.sh
  charts/jx3/jx-preview/defaults.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job.yaml
  packages/jx-cli.yml
Labels: size/S

#1628 fix: upgrade lighthouse, jx-preview, build controller
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jx3/jx-preview/defaults.yaml
Labels: size/XS

#1629 fix: match role and service account names with terraform resources
  charts/cdf/tekton-pipeline/values.yaml.gotmpl
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/tekton/values.yaml.gotmpl
Labels: approved, lgtm, size/S

#1635 fix: upgrade lighthouse + jx-pipelines-visualizer
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/jx-preview/defaults.yaml
Labels: size/XS

#1640 fix: lets add the updatebot label in the PR pipeline
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/defaults.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job.yaml
  packages/jx-cli.yml
  src/Makefile.mk
Labels: size/S

#1642 fix: upgrade LH and UI
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/vault-instance/defaults.yaml
  charts/repositories.yml
Labels: size/XS

#1646 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: size/XS

#1648 fix: upgrade to jx-build-controller chart
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/jx-build-controller/values.yaml.gotmpl
Labels: size/M

#1649 fix: upgrade jx-boot-controller and lighthouse
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jx3/jx-build-controller/defaults.yaml
Labels: size/XS
