Repository jenkins-x/jx3-versions, pull requests merged in 2020-11, with the labels that each got.

#1654 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, size/XS

#1657 fix: chartmuseum getting locked PV when pod updates happen
  charts/jenkins-x/chartmuseum/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/S

#1660 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#1661 fix: upgrade jx and visualizer
  .lighthouse/jenkins-x/release/promote-vs.sh
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job.yaml
  packages/jx-cli.yml
Labels: size/S

#1668 chore: promote version stream to jx3-eks-vault
  .lighthouse/jenkins-x/release/promote-vs.sh
Labels: size/XS

#1664 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jx3/jx-preview/defaults.yaml
Labels: approved, size/XS

#1670 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#1672 fix: optional tls values for pipeline visualiser
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, size/XS

#1674 feat: lets enable /jx chatops commands by default
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#1675 fix: upgraded lighthouse and tekton
  charts/cdf/tekton-pipeline/defaults.yaml
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: size/XS

#1678 fix: add GHE bdd test back again
  .lighthouse/jenkins-x/bdd/ghe/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XL

#1684 fix: fixed issues with map access error where registry key is not specified in cluster config
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, ok-to-test, size/S

#1688 chore: bump more versions # ---:--------------------- >8 ------------------------ # Do not modify or remove the line above. # Everything below it will be ignored.
  .lighthouse/jenkins-x/release/promote-vs.sh
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jx3/jx-test-gc/values.yaml
Labels: approved, size/M

#1693 feat: added in azure value bindings for external dns
  charts/bitnami/external-dns/values.yaml.gotmpl
Labels: needs-ok-to-test, size/XS

#1695 fix: ugprade bucket repository chart
  charts/jenkins-x/bucketrepo/defaults.yaml
  quickstarts.yaml
Labels: size/M

#1696 chore: make sure main cluster ingress domain appears in the external-dns domain filter
  charts/bitnami/external-dns/values.yaml.gotmpl
Labels: approved, size/XS

#1703 fix: switch certmanager to use workload identity when on GCP
  charts/jetstack/cert-manager/values.yaml.gotmpl
  charts/jx3/acme
  charts/jx3/defaults.yaml
Labels: approved, size/XS

#1712 chore: put acme defaults in right folder
  charts/jx3/acme
  charts/jx3/acme/defaults.yaml
Labels: needs-ok-to-test, size/XS

#1732 feat: added in azure.json key for external-dns secret which is generated from requirements values
  charts/bitnami/external-dns/secret-schema.yaml
Labels: needs-ok-to-test, size/S

#1731 fix: add optional force mode
  src/Makefile.mk
Labels: size/S

#1739 fix: fix issue with rolling upgrades causing second pod to be stuck w…
  charts/stable/chartmuseum/values.yaml.gotmpl
Labels: size/XS

#1748 chore: bumped acme chart default versions
  charts/jx3/acme-jx/defaults.yaml
  charts/jx3/acme/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1760 fix: fixed up external-secret chart repo location based on https://github.com/external-secrets/kubernetes-external-secrets/issues/554
  charts/repositories.yml
Labels: approved, lgtm, ok-to-test, size/XS

#1756 chore: upgrade tekton
  charts/cdf/tekton-pipeline/defaults.yaml
Labels: approved, size/XS

#1761 fix: namespaced fake-secrets to avoid collisions with other charts out there
  charts/jenkins-x/chartmuseum/values.yaml.gotmpl
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jenkins-x/nexus/values.yaml.gotmpl
  charts/jenkins-x/tekton/values.yaml.gotmpl
  src/fake-secrets.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/M

#1767 chore: try new bdd bot account and bump jx-cli
  .lighthouse/jenkins-x/bdd/ci.sh
  .lighthouse/jenkins-x/bdd/istio-tls/ci.sh
  .lighthouse/jenkins-x/bdd/istio/ci.sh
  .lighthouse/jenkins-x/bdd/mc/ci.sh
  .lighthouse/jenkins-x/bdd/remote/ci.sh
  .lighthouse/jenkins-x/bdd/storage/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/bdd/tls/ci-old.sh
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release/ci-github.sh
  .lighthouse/jenkins-x/triggers.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job.yaml
  packages/jx-cli.yml
Labels: approved, size/M

#1774 fix(eks): fix wrong iam role for external-dns sa
  charts/bitnami/external-dns/values.yaml.gotmpl
Labels: size/XS

#1776 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  src/Makefile.mk
Labels: size/XS

#1780 fix: lets make sure we shut down the sidecar
  git-operator/job-gsm.yaml
  src/Makefile.mk
Labels: size/XS

#1786 chore: bump cert-manager version
  charts/jetstack/cert-manager/defaults.yaml
Labels: approved, size/XS

#1785 fix: lets clone via: jx gitops git clone
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
Labels: size/L

#1789 feat: if we have enabled TLS lets make the jx secret the default TLS cert used by nginx, this can still be overriden on a per ingress basis
  charts/stable/nginx-ingress/values.yaml.gotmpl
Labels: approved, size/XS

#1790 fix: upgrade old jx versions
  .lighthouse/jenkins-x/pullrequest.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  packages/jx-cli.yml
Labels: approved, size/S

#1795 fix: Add env-var for AWS_REGION
  charts/jx3/jx-build-controller/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#1796 chore: Add annotation for workload identity in AWS
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS
