Repository jenkins-x/jx3-versions, pull requests merged in 2020-12, with the labels that each got.

#1800 fix(pipelines-visualizer): Add env-var for AWS_REGION
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#1806 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
Labels: approved, size/XS

#1812 fix: ugprade jx
  .lighthouse/jenkins-x/bdd/ci.sh
  .lighthouse/jenkins-x/bdd/pipeline-catalog.yaml
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/pullrequest.yaml
  charts/jenkins-x/bucketrepo/defaults.yaml
  charts/jenkins-x/bucketrepo/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  packages/jx-cli.yml
  tests/bucketrepo_test.go
  tests/go.mod
  tests/go.sum
  tests/jxboot_helmfile_resources_test.go
  tests/test_data/expected/bucketrepo-config/config.yaml
Labels: size/L

#1815 feat: added in azurekeyvault boot job
  git-operator/job-azurekeyvault.yaml
Labels: needs-ok-to-test, size/M

#1823 feat: enable nested helmfiles
  .lighthouse/jenkins-x/bdd/ci.sh
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  packages/jx-cli.yml
  src/Makefile.mk
Labels: size/M

#1831 fix: new versions
  charts/ingress-nginx/defaults.yaml
  charts/ingress-nginx/values.yaml.gotmpl
  charts/jenkins-x/chartmuseum/defaults.yaml
  charts/jenkins-x/chartmuseum/values.yaml.gotmpl
  charts/jenkins-x/environment-controller/defaults.yaml
  charts/jenkins-x/exposecontroller-service/defaults.yaml
  charts/jenkins-x/exposecontroller/defaults.yaml
  charts/jenkins-x/jenkins-x-platform/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/prow/defaults.yaml
  charts/jenkins-x/tekton/defaults.yaml
  charts/jenkins-x/tekton/secret-schema.yaml
  charts/jenkins-x/tekton/values.yaml.gotmpl
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/jx-preview/defaults.yaml
  charts/stable/nginx-ingress/defaults.yaml
  charts/stable/nginx-ingress/values.yaml.gotmpl
Labels: approved, size/L

#1840 chore: bump helmfile resources so we can set docker org globally from jx requirements
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
Labels: approved, lgtm, size/XS

#1843 fix: lock down catalog
  .lighthouse/jenkins-x/bdd/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/S

#1845 chore: upgrade preview gc
  charts/jx3/jx-preview/defaults.yaml
Labels: approved, size/XS

#1852 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jx3/jx-preview/defaults.yaml
Labels: approved, size/XS

#1846 feat: enable TLS BDD test
  .lighthouse/jenkins-x/bdd/tls/README.md
  .lighthouse/jenkins-x/bdd/tls/ci-disabled.sh
  .lighthouse/jenkins-x/bdd/tls/ci-old.sh
  .lighthouse/jenkins-x/bdd/tls/ci.sh
  .lighthouse/jenkins-x/bdd/tls/test.sh
  .lighthouse/jenkins-x/triggers.yaml
  charts/bitnami/external-dns/values.yaml.gotmpl
  charts/jetstack/cert-manager/defaults.yaml
  charts/jetstack/cert-manager/values.yaml.gotmpl
  charts/jx3/acme-jx/defaults.yaml
  charts/jx3/acme/defaults.yaml
Labels: approved, size/L

#1855 fix: move to latest LH
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#1859 fix: fix long term storage as we now get logs bucket URL from the cluster requirements
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, size/XS

#1864 fix: upgrade visualizer
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, size/XS

#1867 fix: handle all git providers fixes jenkins-x-plugins/jx-build-contro…
  charts/jx3/jx-build-controller/values.yaml.gotmpl
Labels: approved, size/XS

#1871 fix: upgrade visualiser
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, size/XS

#1872 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
  src/Makefile.mk
Labels: approved, size/XS

#1873 fix: bump external secrets chart version so Azure Key Vault can handle JSON secrets/property selectors
  charts/external-secrets/kubernetes-external-secrets/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1876 chore: update azure version stream template repos
  .lighthouse/jenkins-x/release/promote-vs.sh
Labels: needs-ok-to-test, size/XS

#1882 feat: removed external-dns azure secret from being dependent on ingress.externalDNS. We now create a secret if any DNS config keys are specified in azure section of requirements
  charts/bitnami/external-dns/secret-schema.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1886 fix: missing storage: key when bucket_url is defined
  charts/jenkins-x/bucketrepo/secret-schema.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1895 fix: add better defaults for jenkins integration
  charts/jenkinsci/jenkins/values.yaml.gotmpl
  jenkins/README.md
  jenkins/job-templates/default.xml.gotmpl
  jenkins/templates/README.md
  jenkins/templates/folder.gotmpl
  jenkins/templates/job.gotmpl
  src/Makefile.mk
Labels: approved, size/M

#1902 fix: upgrade jx
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  docker/gcr.io/jenkinsxio/jx-cli.yml
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  packages/jx-cli.yml
  quickstarts.yml
Labels: approved, size/L

#1905 fix: lets generate the jenkins jobs before we resolve helmfile
  src/Makefile.mk
Labels: approved, size/S

#1910 fix: improve the jenkins integration
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkinsci/jenkins/values.yaml.gotmpl
  jenkins/templates/job.gotmpl
Labels: size/M

#1916 fix: upgrade build controller and preview
  charts/cdf/tekton-pipeline/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/jxboot-resources/defaults.yaml
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/jx-preview/defaults.yaml
Labels: size/L

#1917 fix: upgrade tekton
  charts/cdf/tekton-pipeline/defaults.yaml
Labels: approved, size/XS

#1923 fix: exclude pusher-wave Deployment from pusher-wave annotations
  src/Makefile.mk
Labels: approved, lgtm, ok-to-test, size/XS

#1930 chore: upgrade bucketrepo
  charts/jenkins-x/bucketrepo/defaults.yaml
Labels: size/XS

#1929 Git secret server pass as url
  .gitignore
  charts/jx3/jx-build-controller/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#1933 chore: upgrade chart
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
Labels: approved, size/XS
