Repository jenkins-x/jx3-versions, pull requests merged in 2020-08, with the labels that each got.

#1060 fix: better cleanup
  jx/bdd/gke/ci.sh
Labels: size/XS

#1061 fix: refactor bdd tests to share scripts
  jenkins-x-terraform.yml
  jx/bdd/ci.sh
  jx/bdd/gke/ci.sh
  jx/bdd/terraform/ci.sh
Labels: size/L

#1063 fix: auto approve terraform plan
  jenkins-x-gke.yml
  jenkins-x-terraform.yml
  jenkins-x-tls.yml
  jx/bdd/ci.sh
Labels: size/S

#1072 fix: use the new jx test
  jenkins-x-gke.yml
  jenkins-x-terraform.yml
  jenkins-x-tls.yml
  jx/bdd/ci.sh
Labels: size/S

#1077 fix: lets fix the TLS test for now
  apps/jenkins-x/external-dns/values.yaml.gotmpl
  jx/bdd/ci.sh
  jx/bdd/tls/ci-disabled.sh
  jx/bdd/tls/ci.sh
  jx/bdd/tls/test.sh
  kubeProviders/aks/values.yaml.gotmpl
  kubeProviders/alibaba/values.yaml.gotmpl
  kubeProviders/aws/values.yaml.gotmpl
  kubeProviders/eks/values.yaml.gotmpl
  kubeProviders/gke/values.yaml.gotmpl
  kubeProviders/icp/values.yaml.gotmpl
  kubeProviders/iks/values.yaml.gotmpl
  kubeProviders/kubernetes/values.yaml.gotmpl
  kubeProviders/minikube/values.yaml.gotmpl
  kubeProviders/minishift/values.yaml.gotmpl
  kubeProviders/oke/values.yaml.gotmpl
  kubeProviders/openshift/values.yaml.gotmpl
  kubeProviders/pks/values.yaml.gotmpl
Labels: size/L

#1079 fix: use kpt compliant names
  kubeProviders/eks/templates/irsa.yaml.gotmpl
Labels: size/XS

#1086 fix: fix helmfile template regression
  apps/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  jx/bdd/ci.sh
Labels: size/XS

#1089 fix: upgrade jx-cli
  charts/repositories.yml
  docker/gcr.io/jenkinsxio-labs-private/jx-cli.yml
  jenkins-x-gke.yml
Labels: size/XS

#1091 fix: enable GC
  jx/bdd/ci.sh
Labels: size/XS

#1094 fix: use new jx-test
  README.md
  apps/README.md
  apps/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/README.md
  docker/README.md
  git/README.md
  jx/README.md
  jx/bdd/ci.sh
  packages/README.md
Labels: size/M

#1098 chore: first spike at a kind bdd test
  .github/workflows/kind.yml
Labels: size/S

#1100 fix: use better action
  .github/workflows/kind.yml
  apps/stable/docker-registry/values.yaml.gotmpl
  jx/bdd/ci.sh
  jx/bdd/kind/ci.sh
Labels: size/L

#1101 fix: remove old files
  jx/bdd/kind/ci.sh
  kubeProviders/kubernetes/README.md
  kubeProviders/kubernetes/values.yaml.gotmpl
  kubeProviders/minikube/values.yaml.gotmpl
  kubeProviders/minishift/values.yaml.gotmpl
Labels: size/M

#1106 chore: add diagnostics around env vars
  .github/workflows/kind.yml
  jx/bdd/ci.sh
  jx/bdd/kind/ci.sh
Labels: size/M, test/kind

#1117 fix: simplify the BDD test
  jx/bdd/ci.sh
Labels: size/M

#1133 chore: add the gsm workload identity annotation to external secrets service account
  apps/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
Labels: approved, lgtm, size/XS

#1136 fix: lets add the secret schema to the version stream
  charts/bitnami/external-dns/values.yaml.gotmpl
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  charts/flagger/flagger/values.yaml.gotmpl
  charts/flagger/grafana/values.yaml.gotmpl
  charts/jenkins-x/bucketrepo/secret-schema.yaml
  charts/jenkins-x/bucketrepo/values.yaml.gotmpl
  charts/jenkins-x/chartmuseum/secret-schema.yaml
  charts/jenkins-x/chartmuseum/template-values.yaml
  charts/jenkins-x/chartmuseum/values.yaml.gotmpl
  charts/jenkins-x/external-dns/values.yaml.gotmpl
  charts/jenkins-x/jx/values.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/template-values.yaml
  charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  charts/jenkins-x/lighthouse/secret-schema.yaml
  charts/jenkins-x/lighthouse/template-values.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jenkins-x/nexus/secret-schema.yaml
  charts/jenkins-x/nexus/template-values.yaml
  charts/jenkins-x/nexus/values.yaml.gotmpl
  charts/jenkins-x/tekton/secret-schema.yaml
  charts/jenkins-x/tekton/template-values.yaml
  charts/jenkins-x/tekton/values.yaml.gotmpl
  charts/jetstack/cert-manager/values.yaml.gotmpl
  charts/jx-labs/jenkins-x-crds/template-values.yaml
  charts/jx-labs/jenkins-x-crds/values.yaml
  charts/stable/cluster-autoscaler/values.yaml.gotmpl
  charts/stable/docker-registry/values.yaml.gotmpl
  charts/stable/kuberhealthy/values.yaml.gotmpl
  charts/stable/nginx-ingress/values.yaml.gotmpl
  charts/stable/velero/values.yaml.gotmpl
Labels: size/XL

#1137 chore: lets install external secrets in a more generic named namespace
  apps/banzaicloud-stable/vault-operator/defaults.yml
  apps/external-secrets/kubernetes-external-secrets/defaults.yml
  apps/flagger/flagger/defaults.yml
  apps/flagger/grafana/defaults.yml
  apps/jetstack/cert-manager/defaults.yml
  apps/jx-labs/acme/defaults.yml
  apps/jx-labs/flagger-metrics/defaults.yml
  apps/jx-labs/istio/defaults.yml
  apps/jx-labs/jenkins-x-crds/defaults.yml
  apps/jx-labs/vault-instance/defaults.yml
  apps/stable/cluster-autoscaler/defaults.yml
  apps/stable/docker-registry/defaults.yml
  apps/stable/kuberhealthy/defaults.yml
  apps/stable/metrics-server/defaults.yml
  apps/stable/nginx-ingress/defaults.yml
  apps/stable/velero/defaults.yml
  jx/bdd/ci.sh
  jx/bdd/vault/ci.sh
Labels: size/M

#1153 fix: use temp fix for javascript build pack
  docker/gcr.io/jenkinsxio/builder-maven.yml
Labels: size/XS

#1162 fix: add better schemas for bucketrepo/docker registry
  charts/jenkins-x/bucketrepo/secret-schema.yaml
  charts/stable/docker-registry/secret-schema.yaml
Labels: size/M

#1166 fix: upgrade jxboot chart
  charts/jenkins-x/jxboot-helmfile-resources.yml
Labels: approved, size/XS

#1174 fix: add better default pipeline image
  charts/jenkins-x/jxboot-helmfile-resources.yml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  docker/gcr.io/jenkinsxio/builder-maven.yml
Labels: approved, size/XS

#1177 fix: upgrade jxboot chart
  charts/jenkins-x/jxboot-helmfile-resources.yml
Labels: approved, size/XS

#1181 fix: use publishService.enabled instead of extraArgs
  apps/stable/nginx-ingress/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#1182 chore: add official go linter to version stream
  docker/golangci/golangci-lint.yml
Labels: approved, lgtm, size/XS

#1200 fix: upgrade jxboot-helmfile-resources
  charts/jenkins-x/jxboot-helmfile-resources.yml
Labels: size/XS

#1204 fix: add unit tests to verify the secret schema templates
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  jenkins-x.yml
  tests/Makefile
  tests/go.mod
  tests/go.sum
  tests/secret_schema_test.go
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-aks.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-aws.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-eks.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-gke.json
  tests/test_data/expected/jenkins-docker-cfg/config.json/docker-minikube.json
  tests/test_data/expected/jenkins-maven-settings/settingsXml/bucketrepo.xml
  tests/test_data/expected/jenkins-maven-settings/settingsXml/nexus.xml
  tests/test_data/expected/jenkins-maven-settings/settingsXml/none.xml
  tests/test_data/jx-requirements.yml
Labels: size/XXL

#1205 WIP: try java bdd
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  jx/bdd/gke/ci.sh
Labels: do-not-merge/work-in-progress, size/S

#1221 fix: lets move more source into the version stream
  README.md
  git-operator/README.md
  git-operator/job.yaml
  git-operator/resources/README.md
  git-operator/resources/clusterrole.yaml
  git-operator/resources/clusterrolebinding.yaml
  git-operator/resources/sa.yaml
  jenkins-x.yml
  jx/scripts/promote-vs.sh
  jx/scripts/recreate-vs.sh
  secrets/README.md
  secrets/gsm/mapping/secret-mappings.yaml
  secrets/vault/mapping/secret-mappings.yaml
  src/Makefile.mk
  src/README.md
  src/base/cluster/namespaces/jx.yaml
  src/base/kustomization.yaml
  src/base/namespaces/jx/lighthouse-config/install-config-cm.yaml
  src/base/namespaces/jx/source-repositories/README.md
  src/fake-secrets.yaml.gotmpl
  src/kustomization.yaml
  src/production/kustomization.yaml
Labels: size/XL

#1222 fix: remove old cruft
  .jx/gitops/secret-mappings.yaml
Labels: size/S

#1226 fix: lets avoid an extra pipeline run on import
  README.md
  src/Makefile.mk
Labels: size/XS

#1230 fix: lets add the test collector
  charts/presslabs/mysql-operator/secret-schema.yaml
  charts/repositories.yml
  jx/bdd/ci.sh
  src/Makefile.mk
Labels: size/M, test/kind

#1231 fix: polish errors on kind
  .github/workflows/kind.yml
  charts/presslabs/mysql-operator/values.yaml
Labels: size/XS, test/kind

#1233 fix: add a default version for the mysql operator
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  charts/presslabs/mysql-operator/defaults.yaml
  git-operator/job.yaml
  jenkins-x-gke.yml
  jenkins-x-terraform.yml
  jenkins-x-tls.yml
  jx/bdd/ci.sh
  tests/go.sum
Labels: approved, size/S, test/kind

#1239 fix: for kind
  .github/workflows/kind.yml
  charts/jx3/jenkins-x-crds/defaults.yaml
  charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  jx/bdd/ci.sh
  jx/bdd/kind/ci.sh
Labels: size/S, test/kind

#1244 fix: kind bdd test
  charts/jx3/jenkins-x-crds/defaults.yaml
  charts/jx3/jenkins-x-crds/values.yaml.gotmpl
Labels: size/XS
