Repository jenkins-x/jx3-versions, pull requests merged in 2021-05, with the labels that each got.

#2457 fix: trigger restart of lighthouse on boot job
  src/Makefile.mk
Labels: approved, size/XS

#2460 fix: reuse secret name for pipeline visualiser
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, size/XS

#2461 chore: add lighthouse-telemetry-plugin
  charts/jx3/lighthouse-telemetry-plugin/defaults.yaml
  charts/jx3/lighthouse-telemetry-plugin/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2469 fix: lets ensure we setup the git user/email correctly
  src/Makefile.mk
Labels: approved, size/XS

#2480 chore: upgrade external-dns chart version
  charts/bitnami/external-dns/defaults.yaml
Labels: approved, size/XS

#2484 fix: try kubetest on environment PRs
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/M

#2488 feat: support jx-requirements log url with a querystring
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/S

#2496 fix: add support for copying the boot secrets
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  src/Makefile.mk
Labels: approved, size/S

#2498 feat: Add initial MLOps assets to versionStream
  mlprojectsets.yaml
  mlquickstarts.yaml
Labels: size/M

#2506 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2512 chore: add argo defaults
  charts/argocd/argocd/defaults.yaml
  charts/argocd/argocd/values.yaml.gotmpl
  charts/repositories.yml
Labels: approved, size/S

#2514 fix: avoid modifying git with the git sha
  src/Makefile.mk
Labels: approved, size/XS

#2517 fix: better support for maven + bucketrepo
  charts/jx3/jxboot-helmfile-resources/secret-schema.yaml
Labels: size/XS

#2524 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS

#2528 fix: switch to latest bucketrepo
  charts/jenkins-x/bucketrepo/defaults.yaml
  charts/jenkins-x/bucketrepo/values.yaml.gotmpl
  charts/jx3/bucketrepo/secret-schema.yaml
Labels: approved, size/S

#2537 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS

#2534 feat: Migrate mlquickstarts
  mlprojectsets.yaml
  mlquickstarts.yaml
Labels: size/L

#2538 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2544 feat: added aws secrets configuration
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  secrets/secretsManager/mapping/secret-mappings.yaml
  secrets/systemManager/mapping/secret-mappings.yaml
Labels: approved, lgtm, ok-to-test, size/L

#2545 fix: updated role names for aws secrets
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/S

#2551 chore: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2555 fix: upgrade tekton
  charts/cdf/tekton-pipeline/defaults.yaml
  charts/cdf/tekton-pipeline/values.yaml.gotmpl
  src/Makefile.mk
Labels: approved, size/S

#2557 fix: increase polling interval if we're using Azure Key Vault
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/M
