Repository jenkins-x/jx3-versions, pull requests merged in 2021-07, with the labels that each got.

#2662 chore: bumb jx health checks chart veersion
  charts/jxgh/health-checks-jx/defaults.yaml
Labels: approved, size/XS

#2688 fix: re-enable CI
  .lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/XS

#2691 chore: lets get external dns to cleanup A records when ingress rules …
  charts/bitnami/external-dns/values.yaml.gotmpl
Labels: approved, size/XS

#2694 fix: make hmac optional for bitbucketcloud
  charts/jx3/lighthouse-webui-plugin/values.yaml.gotmpl
Labels: approved, ok-to-test, size/S

#2703 fix: allow prometheus to scrape tempo metrics
  charts/grafana/tempo/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2705 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/S

#2707 fix: always enable --issuer-ambient-credentials in cert-manager
  charts/jetstack/cert-manager/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2708 chore: improve cert-manager values
  charts/jetstack/cert-manager/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2714 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2716 fix: use correct jx image
  charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
Labels: approved, size/XS
