Repository jenkins-x/jx3-versions, pull requests merged in 2021-09, with the labels that each got.

#2769 fix: use central as default mirror
  charts/jxgh/jxboot-helmfile-resources/secret-schema.yaml
Labels: size/XS, approved, lgtm, ok-to-test

#2777 chore: switch to new release infra
  .lighthouse/jenkins-x/bdd/bbc/ci.sh
  .lighthouse/jenkins-x/bdd/bbs/ci.sh
  .lighthouse/jenkins-x/bdd/ghe/ci.sh
  .lighthouse/jenkins-x/bdd/gitea/ci.sh
  .lighthouse/jenkins-x/bdd/gitlab/ci.sh
  .lighthouse/jenkins-x/bdd/gsm-kapp/ci.sh
  .lighthouse/jenkins-x/bdd/gsm/ci.sh
  .lighthouse/jenkins-x/bdd/istio-tls/ci.sh
  .lighthouse/jenkins-x/bdd/istio/ci.sh
  .lighthouse/jenkins-x/bdd/kube/ci.sh
  .lighthouse/jenkins-x/bdd/kubevault/ci.sh
  .lighthouse/jenkins-x/bdd/multi/ci.sh
  .lighthouse/jenkins-x/bdd/remote/ci.sh
  .lighthouse/jenkins-x/bdd/remote/cluster.yaml
  .lighthouse/jenkins-x/bdd/storage/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/tls/ci.sh
  .lighthouse/jenkins-x/bdd/tls/test.sh
  .lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/M

#2779 chore: remove references to old jx chart repo
  charts/jenkins-x/README.md
  charts/jenkins-x/nexus/values.yaml.gotmpl
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
  charts/repositories.yml
Labels: size/S, approved

#2788 refactor: upgrade external secrets to 8.3.0
  charts/external-secrets/kubernetes-external-secrets/defaults.yaml
Labels: size/XS, approved

#2792 feat: set url from requirements file for external vault
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
Labels: size/XS, approved, lgtm

#2793 fix: run vault login in external secrets init container
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
Labels: size/S, approved
