Repository jenkins-x/jx3-versions, pull requests merged in 2021-04, with the labels that each got.

#2334 chore: bump pipeline catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2337 chore: add defaults for grafana tempo
  charts/grafana/grafana/values.yaml.gotmpl
  charts/grafana/tempo/defaults.yaml
  charts/grafana/tempo/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#2340 chore: link jx-pipelines-visualizer with grafana
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/S

#2346 feat: enable tracing in build-controller
  charts/jx3/jx-build-controller/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2355 fix: lets avoid terraform removing k8s resources
  .lighthouse/jenkins-x/bdd/terraform-bbc.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-multi-dev.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-multi-prod.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
Labels: approved, size/M

#2358 fix: upgrade lighthouse and use main branch for BDD
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/lighthouse/defaults.yaml
  git/github.com/jenkins-x-buildpacks/jenkins-x-classic.yml
  git/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.yml
  git/github.com/jenkins-x-labs/cloud-resources.yml
  git/github.com/jenkins-x/jenkins-x-boot-config.yml
  git/github.com/jenkins-x/jxr-packs-kubernetes.yml
  git/github.com/jenkins-x/terraform-aws-eks-jx.yml
  git/github.com/jenkins-x/terraform-azurerm-jx.yml
  git/github.com/jenkins-x/terraform-google-jx.yml
Labels: approved, size/M

#2365 fix: lets use the version stream terraform modules
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/pullrequest-bbc.yaml
  .lighthouse/jenkins-x/pullrequest-bbs.yaml
  .lighthouse/jenkins-x/pullrequest-eks.yaml
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/pullrequest-gitea.yaml
  .lighthouse/jenkins-x/pullrequest-gitlab.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M

#2367 chore: add kube vault BDD
  .lighthouse/jenkins-x/bdd/kubevault/README.md
  .lighthouse/jenkins-x/bdd/kubevault/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-kubevault.yaml.gotmpl
  .lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/L

#2370 chore: add an oauth2 proxy chart + defaults to allow oauth for pipeli…
  charts/k8s-at-home/oauth2-proxy/defaults.yaml
  charts/k8s-at-home/oauth2-proxy/secret-schema.yaml
  charts/k8s-at-home/oauth2-proxy/values.yaml.gotmpl
  charts/repositories.yml
Labels: approved, size/M

#2375 fix: lets only recreate the htpasswd secret if empty
  charts/jx3/jxboot-helmfile-resources/secret-schema.yaml
  git/github.com/jenkins-x-terraform/terraform-jx-azure.yml
  git/github.com/jenkins-x/terraform-aws-eks-jx.yml
  git/github.com/jenkins-x/terraform-azurerm-jx.yml
Labels: approved, size/S

#2382 fix: upgrade pipeline catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/M

#2388 fix: upgrade updatebot
  charts/jx3/jxboot-helmfile-resources/defaults.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2389 chore: upgrade jxboot-helmfile chart
  charts/jx3/jxboot-helmfile-resources/defaults.yaml
Labels: approved, size/XS

#2404 fix: add better defaults for jenkins
  charts/jenkinsci/jenkins/values.yaml.gotmpl
Labels: approved, size/S

#2413 fix: upgrade terraform
  git/github.com/jenkins-x/terraform-google-jx.yml
Labels: approved, size/S

#2425 fix: move report generation into the main build
  src/Makefile.mk
Labels: approved, size/XS

#2434 fix: better handling of report and status
  src/Makefile.mk
Labels: approved, size/S

#2440 fix: lets switch to stackdriver for GKE
  charts/jx3/jx-build-controller/values.yaml.gotmpl
  charts/jx3/lighthouse/values.yaml.gotmpl
Labels: approved, size/S

#2441 fix: ensure grafana secret checksum won't change every time
  charts/grafana/grafana/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS
