Repository jenkins-x/jx3-versions, pull requests merged in 2021-01, with the labels that each got.

#1934 chore: upgrade build controller
  charts/jx3/jx-build-controller/defaults.yaml
Labels: size/XS

#1935 feat: added in kapp application rather than kubectl
  src/Makefile.mk
Labels: approved, lgtm, ok-to-test, size/S

#1941 chore: upgrade vault instance
  charts/jx3/vault-instance/defaults.yaml
Labels: size/XS

#1943 fix: upgrade to the latest LH
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#1944 fix: upgrade charts
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkinsci/jenkins/values.yaml.gotmpl
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, size/XS

#1948 chore: upgrade lighthouse and jx-preview
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jx3/jx-preview/defaults.yaml
Labels: approved, size/XS

#1950 fix: upgrade dashboard
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, size/XS

#1961 fix: upgrade helmfile-resources + build controller
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: size/XS

#1962 fix: upgrade dashboard
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, size/XS

#1970 feat: put values templating in for azure storage account on jx build controller
  charts/jx3/jx-build-controller/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#1977 fix: upgrade dashboard and catalog
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS

#1965 fix: upgrade vault chart
  charts/banzaicloud-stable/vault-operator/defaults.yaml
  charts/jx3/vault-instance/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1979 chore: update health checks
  charts/jx3/health-checks-install/defaults.yaml
  charts/jx3/health-checks-install/values.yaml.gotmpl
  charts/jx3/health-checks-jx/defaults.yaml
  charts/jx3/health-checks-jx/values.yaml.gotmpl
Labels: approved, size/S

#1978 fix: upgrade jxboot-helmfile-resources chart
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
Labels: approved, size/XS

#1966 fix: upgrade external-dns chart
  charts/bitnami/external-dns/defaults.yaml
Labels: approved, ok-to-test, size/XS

#1984 fix: upgrade preview
  charts/jx3/jx-preview/defaults.yaml
Labels: approved, size/XS

#1985 chore: bump jx build controller version
  charts/jx3/jx-build-controller/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1986 fix: upgrade tekton
  charts/cdf/tekton-pipeline/defaults.yaml
Labels: approved, size/XS

#1991 fix: use explicit namespace for registry secret
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
Labels: approved, size/XS

#1989 chore: bump acme chart
  charts/jx3/acme-jx/defaults.yaml
  charts/jx3/acme/defaults.yaml
Labels: approved, size/XS

#1995 chore: upgrade charts
  charts/jenkins-x/jx-build-templates/defaults.yaml
  charts/jenkins-x/jx/defaults.yaml
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/nexus/defaults.yaml
  charts/jenkins-x/sso-operator/defaults.yaml
  charts/jx3/jx-cli/defaults.yaml
  charts/jx3/jx-kh-check/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/slack/defaults.yaml
Labels: approved, size/S

#1998 feat: add in azure storage account env var to pipeline vizualizer so it knows where to retrieve logs from
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2000 chore: bump jx-pipeline-visualizer default version
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2008 fix: include the release name in helmfile template
  src/Makefile.mk
Labels: approved, lgtm, ok-to-test

#2015 fix: avoid failing if no azure storage
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, size/XS

#2022 fix: increased delay between templating a repo and cloning it too reduce CI errors
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
Labels: approved, lgtm, ok-to-test, size/XS

#2021 chore: upgrade charts
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/jx-cli/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/jx-preview/defaults.yaml
Labels: size/S, updatebot

#2018 chore: Bump up chartmuseum version
  charts/stable/chartmuseum/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2029 chore: upgrade charts
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jx3/jx-build-controller/defaults.yaml
  charts/jx3/jx-cli/defaults.yaml
  charts/jx3/jx-preview/defaults.yaml
Labels: size/XS, updatebot

#2032 feat: added in secret env var map for azure key vault job
  git-operator/job-azurekeyvault.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2037 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse/defaults.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  charts/jx3/jx-build-controller/defaults.yaml
Labels: approved, size/XS

#2057 chore: upgrade to new jx-boot image
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
Labels: approved, size/S

#2059 chore: upgrade pipeline catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/M

#2063 chore: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS
