Repository jenkins-x/jx3-versions, pull requests merged in 2021-03, with the labels that each got.

#2197 fix: use a less noisy makefile
  src/Makefile.mk
Labels: approved, size/L

#1827 refactor: remove deprecated certmanager chart
  charts/stable/cert-manager/defaults.yaml
Labels: approved, lgtm, size/XS

#2205 fix: switch to new BDD project
  .lighthouse/jenkins-x/bdd/bbs/ci.sh
  .lighthouse/jenkins-x/bdd/ghe/ci.sh
  .lighthouse/jenkins-x/bdd/gsm-kapp/ci.sh
  .lighthouse/jenkins-x/bdd/gsm/ci.sh
  .lighthouse/jenkins-x/bdd/istio-tls/ci.sh
  .lighthouse/jenkins-x/bdd/istio/ci.sh
  .lighthouse/jenkins-x/bdd/kube/ci.sh
  .lighthouse/jenkins-x/bdd/mc/ci.sh
  .lighthouse/jenkins-x/bdd/remote/ci.sh
  .lighthouse/jenkins-x/bdd/remote/cluster.yaml
  .lighthouse/jenkins-x/bdd/storage/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/bdd/tls/ci.sh
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  src/Makefile.mk
Labels: approved, size/M

#2209 fix: make it easier to disable scheduler generation
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  src/Makefile.mk
Labels: approved, size/S

#2211 fix: switch to the new jxboot-helmfile-resources chart
  .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest-bbs.yaml
  .lighthouse/jenkins-x/pullrequest-eks.yaml
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/pullrequest-gitlab.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/jx3/jxboot-helmfile-resources/defaults.yaml
  charts/jx3/jxboot-helmfile-resources/secret-schema.yaml
  charts/jx3/jxboot-helmfile-resources/values.yaml.gotmpl
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  packages/jx-cli.yml
  src/Makefile.mk
Labels: approved, size/L

#2214 chore: lets try BBS test
  .github/workflows/bdd-kind/ci.sh
  .lighthouse/jenkins-x/triggers.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  src/Makefile.mk
Labels: approved, size/L

#2238 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/S

#2230 fix: add BDD test for gitea
  .lighthouse/jenkins-x/bdd/gitea/README.md
  .lighthouse/jenkins-x/bdd/gitea/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest-gitea.yaml
  .lighthouse/jenkins-x/triggers.yaml
  charts/repositories.yml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/L

#2242 fix: report deploy status to github
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  src/Makefile.mk
Labels: size/XS

#2245 feat: add grafana stack
  charts/grafana/grafana/defaults.yaml
  charts/grafana/grafana/values.yaml.gotmpl
  charts/grafana/loki/defaults.yaml
  charts/grafana/loki/values.yaml
  charts/grafana/promtail/defaults.yaml
  charts/grafana/promtail/values.yaml
  charts/prometheus-community/prometheus/defaults.yaml
  charts/prometheus-community/prometheus/values.yaml
Labels: approved, lgtm, ok-to-test, size/L

#2250 chore: enable prometheus scraping for nginx-ingress controller
  charts/ingress-nginx/ingress-nginx/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2247 chore: enable prometheus scraping for lighthouse
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/S

#2248 chore: enable prometheus scraping for external-dns
  charts/bitnami/external-dns/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2249 chore: enable prometheus scraping for external-secrets
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2256 chore: add grafana-dashboard chart
  charts/jx3/grafana-dashboard/defaults.yaml
  charts/jx3/grafana-dashboard/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2257 feat: allow pipelines-visualizer to get pipelineruns from longterm storage
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2246 chore: enable prometheus scraping for tekton
  charts/cdf/tekton-pipeline/defaults.yaml
  charts/cdf/tekton-pipeline/values.yaml.gotmpl
Labels: approved, ok-to-test, size/XS

#2262 chore: upgrade kuberhealthy & enable prometheus scraping
  charts/kuberhealthy/kuberhealthy/defaults.yaml
  charts/kuberhealthy/kuberhealthy/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2264 chore: configure grafana & prometheus for alerting
  charts/grafana/grafana/values.yaml.gotmpl
  charts/jx3/grafana-dashboard/defaults.yaml
  charts/prometheus-community/prometheus/values.yaml
Labels: approved, lgtm, ok-to-test

#2261 chore: remove unused grafana & prometheus charts
  charts/stable/grafana/defaults.yaml
  charts/stable/prometheus/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2268 fix: move to new lighthouse release
  .lighthouse/jenkins-x/bdd/terraform-bbc.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest-bbc.yaml
  .lighthouse/jenkins-x/pullrequest-bbs.yaml
  .lighthouse/jenkins-x/pullrequest-eks.yaml
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/pullrequest-gitea.yaml
  .lighthouse/jenkins-x/pullrequest-gitlab.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/jx3/lighthouse/defaults.yaml
  charts/jx3/lighthouse/secret-schema.yaml
  charts/jx3/lighthouse/values.yaml.gotmpl
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  packages/jx-cli.yml
Labels: approved, size/M

#2270 fix: add missing mapping for prometheus helm repository
  charts/repositories.yml
Labels: approved, lgtm, ok-to-test, size/XS

#2281 chore: cleanup lighthouse values
  charts/jx3/lighthouse/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2287 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS

#2290 fix: upgrade to latest catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2298 chore: add cd-indicators chart
  charts/jx3/cd-indicators/defaults.yaml
  charts/jx3/cd-indicators/secret-schema.yaml
  charts/jx3/cd-indicators/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#2295 fix: add a BDD test for multi cluster
  .lighthouse/jenkins-x/bdd/mc/README.md
  .lighthouse/jenkins-x/bdd/mc/ci.sh
  .lighthouse/jenkins-x/bdd/multi/README.md
  .lighthouse/jenkins-x/bdd/multi/ci.sh
  .lighthouse/jenkins-x/bdd/multi/overlay.sh
  .lighthouse/jenkins-x/bdd/multi/requirements-overlay.yaml
  .lighthouse/jenkins-x/bdd/terraform-multi-dev.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-multi-prod.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/L

#2306 feat: add default values for osiris
  charts/osiris/osiris/defaults.yaml
  charts/osiris/osiris/values.yaml.gotmpl
  charts/repositories.yml
Labels: approved, lgtm, ok-to-test, size/S

#2307 chore: register cd-indicators as an ext lighthouse plugin
  schedulers/default.yaml
  schedulers/environment.yaml
  schedulers/in-repo.yaml
  schedulers/jx-meta-pipeline.yaml
Labels: approved, lgtm, ok-to-test, size/S

#2309 fix: avoid issues with external-dns when no environments
  .lighthouse/jenkins-x/release.yaml
  charts/bitnami/external-dns/values.yaml.gotmpl
Labels: approved, size/XS
