Repository jenkins-x/jx3-versions, pull requests merged in 2021-02, with the labels that each got.

#2079 fix: make sure Jenkins only scans mainline branches and pull requests, also support TLS ingress rule for Jenkins
  charts/jenkinsci/jenkins/values.yaml.gotmpl
  jenkins/templates/job.gotmpl
Labels: approved, lgtm, size/S

#2082 fix: configure the pipelines-visualizer to access the logs storage
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/S

#2091 fix: upgrade the rust catalog and quickstart
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  quickstarts.yaml
  src/Makefile.mk
Labels: approved, size/S

#2090 fix: add serviceaccount annotation, env for aws region, set base dir …
  charts/jenkins-x/bucketrepo/secret-schema.yaml
  charts/jenkins-x/bucketrepo/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/S

#2097 chore: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS

#2098 chore: upgrade the catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2074 feat: run jx secret populate earlier in boot sequence
  .lighthouse/jenkins-x/bdd/vault/ci.sh
  charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  charts/jenkins-x/bucketrepo/secret-schema.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  src/Makefile.mk
Labels: approved, ok-to-test, size/M

#2110 chore: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, lgtm, size/XS

#2112 fix: nexus password missing from maven settings xml when using gsm
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
Labels: size/M

#2121 fix: switch to new bdd approach
  .lighthouse/jenkins-x/bdd/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/M

#2127 chore: disable lighthouse hmac if bitbucket cloud
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
Labels: size/XS

#2132 fix: switch to terraform operator
  .lighthouse/jenkins-x/bdd/ci.sh
  .lighthouse/jenkins-x/bdd/kube/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml
  .lighthouse/jenkins-x/bdd/terraform.yaml
  .lighthouse/jenkins-x/bdd/tls/ci.sh
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  packages/jx-cli.yml
Labels: approved, size/XL

#2142 feat: configured jxboot-helmfile-resources secret schema to pull from external secret locations rather than k8s so they populate prior to applying k8s resources
  .lighthouse/jenkins-x/pullrequest.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
Labels: approved, ok-to-test, size/M

#2147 fix: test new check-registry step
  .lighthouse/jenkins-x/bdd/eks/README.md
  .lighthouse/jenkins-x/bdd/eks/ci.sh
  .lighthouse/jenkins-x/bdd/kube/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/tls/ci.sh
  .lighthouse/jenkins-x/pullrequest-eks.yaml
  .lighthouse/jenkins-x/release/promote-vs.sh
  .lighthouse/jenkins-x/triggers.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/L

#2150 fix: upgrade jx and BDD tests
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest-eks.yaml
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/jenkins-x/jxboot-helmfile-resources/secret-schema.yaml
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  packages/jx-cli.yml
Labels: size/M

#2148 feat: revert back to external-secrets main chart repo
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest-eks.yaml
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  packages/jx-cli.yml
Labels: approved, lgtm, ok-to-test, size/M

#2153 chore: upgrade jx
  .lighthouse/jenkins-x/bdd/eks/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
  charts/jx3/jx-build-controller/values.yaml.gotmpl
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/L

#2157 chore: add a base grafana chart so we can capture health checks
  charts/grafana/defaults.yaml
  charts/grafana/secret-schema.yaml
  charts/grafana/values.yaml.gotmpl
  charts/repositories.yml
Labels: approved, size/M

#2163 fix: use the correct jx version for bdd tests
  .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
Labels: approved, size/S

#2169 chore: move grafana into correct chart sub dir so values can resolve
  charts/grafana/grafana/defaults.yaml
  charts/grafana/grafana/secret-schema.yaml
  charts/grafana/grafana/values.yaml.gotmpl
Labels: approved, size/XS

#2168 fix: add bdd test for kapp
  .lighthouse/jenkins-x/bdd/gsm-kapp/README.md
  .lighthouse/jenkins-x/bdd/gsm-kapp/ci.sh
  .lighthouse/jenkins-x/bdd/gsm-kapp/job-overlay.yaml
  .lighthouse/jenkins-x/bdd/gsm-kapp/overlay.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/triggers.yaml
  charts/jenkins-x/lighthouse/values.yaml.gotmpl
  src/Makefile.mk
Labels: size/M

#2179 fix: upgrade jxboot-helmfile-templates
  charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
Labels: approved, size/XS

#2182 fix: upgrade catalog
  .lighthouse/jenkins-x/bdd/bbs/README.md
  .lighthouse/jenkins-x/bdd/bbs/ci.sh
  .lighthouse/jenkins-x/bdd/bbs/setup.sh
  .lighthouse/jenkins-x/bdd/vault-kapp/README.md
  .lighthouse/jenkins-x/bdd/vault-kapp/ci.sh
  .lighthouse/jenkins-x/bdd/vault-kapp/job-overlay.yaml
  .lighthouse/jenkins-x/bdd/vault-kapp/overlay.sh
  .lighthouse/jenkins-x/pullrequest-bbs.yaml
  .lighthouse/jenkins-x/triggers.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/L

#2184 feat: added in optional boot env vars that are populated by terraform or as part of cluster pre-reqs
  git-operator/job.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2194 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS
