Repository jenkins-x/jx3-versions, pull requests merged in 2021-06, with the labels that each got.

#2560 fix: MNIST dataset location has changed
  mlprojectsets.yaml
  mlquickstarts.yaml
Labels: approved, lgtm, size/S

#2564 fix: retrigger PR pipelines on merge by default
  charts/jx3/lighthouse/values.yaml.gotmpl
Labels: approved, size/XS

#2568 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS

#2572 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2579 chore: add lighthouse-webui-plugin
  charts/jx3/lighthouse-webui-plugin/defaults.yaml
  charts/jx3/lighthouse-webui-plugin/values.yaml
Labels: approved, ok-to-test, size/M

#2580 chore: upgrade osiris to 0.0.55
  charts/osiris/osiris/defaults.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2584 chore: configure the lighthouse web ui
  schedulers/default.yaml
  schedulers/environment.yaml
  schedulers/in-repo.yaml
  schedulers/jx-meta-pipeline.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2585 chore: add the lighthouse webui to the default oauth hosts
  charts/k8s-at-home/oauth2-proxy/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/XS

#2588 chore: rename go template file name
  charts/jx3/lighthouse-webui-plugin/values.yaml.gotmpl
Labels: approved, size/XS

#2593 fix: force push PRs on environments
  src/Makefile.mk
Labels: approved, size/XS

#2597 chore(lighthouse-webui-plugin): enable persistence by default
  charts/jx3/lighthouse-webui-plugin/values.yaml.gotmpl
Labels: approved, lgtm, ok-to-test, size/S

#2598 chore: use the new LH webui when reporting status updates
  schedulers/default.yaml
  schedulers/environment.yaml
  schedulers/in-repo.yaml
  schedulers/jx-meta-pipeline.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2616 fix: upgrade catalog and UIs
  charts/jx3/jx-pipelines-visualizer/defaults.yaml
  charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  charts/jx3/lighthouse-webui-plugin/defaults.yaml
  charts/jx3/lighthouse-webui-plugin/values.yaml.gotmpl
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/S

#2627 fix: add new quickstart
  quickstarts.yaml
Labels: approved, size/XS

#2619 fix: use external secrets name as standard
  charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  secrets/systemManager/mapping/secret-mappings.yaml
Labels: ok-to-test, size/S

#2630 fix: upgrade catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2631 chore: bump catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/XS

#2632 fix: disable secret populate on PRs
  src/Makefile.mk
Labels: size/XS
