Repository jenkins-x/jx3-versions, pull requests merged in 2022-08, with the labels that each got.

#3246 fix: modify tf yaml after tf operator upgrade
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: approved, size/M

#3270 chore: specify vault role & mount point for populate and es
  src/Makefile.mk
Labels: size/S, approved, needs-ok-to-test

#3256 fix: only apply CRDs if they exist
  src/Makefile.mk
Labels: size/XS, approved, lgtm, ok-to-test
