Repository jenkins-x/jx3-versions, pull requests merged in 2022-06, with the labels that each got.

#3127 chore: Upgrade external-dns
  charts/bitnami/external-dns/defaults.yaml
Labels: size/XS, approved

#3136 fix: disable kuberhealthy installation to fix issues with k8s 1.22+
  .gitignore
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  git/github.com/jenkins-x/terraform-google-jx.yml
Labels: size/S

#3122 fix: auto update nginx helm chart
  .github/workflows/update-charts/updatebot.yaml
Labels: size/XS, approved

#3143 chore: Upgrade jx3-pipeline-catalog
  OWNERS
  OWNERS_ALIASES
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/S, approved

#3178 chore: upgrade terraform versionstream
  git/github.com/jenkins-x-terraform/terraform-jx-azure.yml
Labels: size/S, approved

#3202 fix: Don't download context
  .lighthouse/jenkins-x/bdd/remote/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-bbc.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kubevault.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-multi-dev.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-multi-prod.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
Labels: size/S, approved

#3206 fix: Prevent jx scm from overwriting release notes
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved
