Repository jenkins-x/jx3-versions, pull requests merged in 2022-03, with the labels that each got.

#2971 chore: manually bump charts other than tkn
  charts/jxgh/jx-build-controller/defaults.yaml
  charts/jxgh/jx-preview/defaults.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS, approved, lgtm

#2884 fix: Upgrade cert-manager to 1.2.0
  charts/jetstack/cert-manager/defaults.yaml
Labels: size/XS, approved, ok-to-test

#2987 chore: upgrade all charts except tkn
  charts/jxgh/jx-build-controller/defaults.yaml
  charts/jxgh/jx-preview/defaults.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS, approved, lgtm

#2991 chore: upgrade all charts except tkn
  charts/jxgh/jx-build-controller/defaults.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS, approved
