Repository jenkins-x/jx3-versions, pull requests merged in 2022-10, with the labels that each got.

#3359 Feat: add tekton chains integration
  charts/chainguard-dev/tekton-chains/defaults.yaml
  charts/chainguard-dev/tekton-chains/values.yaml.gotmpl
Labels: approved, size/M

#3378 feat: Make update of webhooks fast
  src/Makefile.mk
Labels: size/XS, approved

#3376 chore: manual bump of charts
  charts/jxgh/jx-preview/defaults.yaml
  charts/jxgh/jx-slack/defaults.yaml
  charts/jxgh/jx-ui/defaults.yaml
  charts/jxgh/vault-instance/defaults.yaml
Labels: size/XS, approved

#3380 fix: Remove references to non-existing plugins
  schedulers/default.yaml
  schedulers/environment-review-required.yaml
  schedulers/environment.yaml
  schedulers/in-repo.yaml
  schedulers/jx-meta-pipeline.yaml
Labels: size/S, approved

#3386 fix: manually bump catalog version to upgrade to updatebot 0.3.6
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS, approved

#3387 feat: add external secrets charts
  charts/external-secrets/external-secrets/defaults.yaml
  charts/external-secrets/external-secrets/values.yaml.gotmpl
Labels: approved, size/M

#3394 chore: Upgrade jx-updatebot
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/M

#3223 feat: Add support for kpt live apply
  charts/cdf/tekton-pipeline/defaults.yaml
  src/Makefile.mk
  src/kpt-live-apply-wrapper.sh
Labels: size/L, approved

#3395 feat: add selector option to Makefile. Regenerate only namespace with changes
  src/Makefile.mk
  src/get-selectors-and-clean.sh
Labels: approved, size/M, ok-to-test
