Repository jenkins-x/jx3-versions, pull requests merged in 2022-07, with the labels that each got.

#3216 fix: use spot instances instead of pre-emptible
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
Labels: size/XS, approved

#3217 fix: downgrade ex-dns to 6.4.5
  charts/bitnami/external-dns/defaults.yaml
Labels: size/XS, approved, lgtm

#3233 chore: disable tekton chart auto upgrade
  .github/workflows/update-charts/updatebot.yaml
Labels: size/XS, approved

#3240 refactor: upgrade pipeline catalog sha to upgrade go version
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/M

#3242 fix: upgrade cert manager to 1.9.1
  charts/jetstack/cert-manager/defaults.yaml
Labels: size/XS, approved
