Repository jenkins-x/jx3-versions, pull requests merged in 2022-09, with the labels that each got.

#3288 fix: Verify pod result
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
Labels: size/S, approved

#3291 chore(deps): upgrade jenkins-x/lighthouse to version 1.9.0
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  charts/jxgh/lighthouse/defaults.yaml
Labels: updatebot, size/XS

#3293 fix: Improve log output
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
Labels: size/S, approved

#3296 feat: update version for catalog
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS, approved, ok-to-test

#3300 fix: edit catalog reference
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: size/XS, approved

#3306 fix: use HELMFILE_TEMPLATE_FLAGS in 'helmfile template'
  src/Makefile.mk
Labels: size/XS, approved, ok-to-test

#3332 chore: upgrade tekton chart to 0.1.0
  charts/cdf/tekton-pipeline/defaults.yaml
Labels: size/XS, approved

#3341 fix: Switch to remote environment pipelines
  .lighthouse/jenkins-x/release/promote-vs.sh
Labels: size/S, approved

#3347 feat: add jx ui chart to version stream
  charts/jxgh/jx-ui/defaults.yaml
  charts/jxgh/jx-ui/values.yaml.gotmpl
Labels: approved, size/M
