Repository jenkins-x/jx3-versions, pull requests merged in 2022-04, with the labels that each got.

#2998 chore: bump all charts except tekton
  charts/jxgh/jx-build-controller/defaults.yaml
  charts/jxgh/jx-preview/defaults.yaml
  charts/jxgh/jx-slack/defaults.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS

#3003 fix: clean up owners file and update jxboot-helmfile chart
  OWNERS
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/S

#3005 chore: update jxboot helmfile chart
  .github/workflows/bdd-kind.yml
  .github/workflows/update-charts.yml
  .github/workflows/update-go.yml
  .lighthouse/jenkins-x/bdd/terraform-bbc.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-bbs.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-eks.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-ghe.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitea.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-gitlab.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kube.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-kubevault.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-multi-dev.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-multi-prod.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform-tls.yaml.gotmpl
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
  .lighthouse/jenkins-x/pullrequest-bbc.yaml
  .lighthouse/jenkins-x/pullrequest-bbs.yaml
  .lighthouse/jenkins-x/pullrequest-eks.yaml
  .lighthouse/jenkins-x/pullrequest-ghe.yaml
  .lighthouse/jenkins-x/pullrequest-gitea.yaml
  .lighthouse/jenkins-x/pullrequest-gitlab.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
  git-operator/job-azurekeyvault.yaml
  git-operator/job-gsm.yaml
  git-operator/job-vault.yaml
  git-operator/job.yaml
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  packages/jx.yml
Labels: approved, size/XXL

#3012 chore: upgrade cert manager cert to 1.3.3
  charts/jetstack/cert-manager/defaults.yaml
Labels: size/XS, approved

#3023 chore: update certmanager to 1.4.4
  charts/jetstack/cert-manager/defaults.yaml
  charts/jxgh/jx-preview/defaults.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS, approved

#3031 refactor: upgrade jxboot helmfile chart to 1.1.66
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS, approved

#3032 chore: upgrade catalog to get go 1.17.9 in versionstream
  git/github.com/jenkins-x/jx3-pipeline-catalog.yml
Labels: approved, size/M

#3035 chore: upgrade cert-manager to 1.5.5
  charts/jetstack/cert-manager/defaults.yaml
Labels: size/XS, approved, lgtm

#3036 chore: update dependencies
  charts/jxgh/jx-preview/defaults.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS, approved

#3047 feat: switch to pre-emptible nodes to lower costs
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
Labels: size/XS, approved

#3051 chore: upgrade charts
  charts/jxgh/jx-preview/defaults.yaml
  charts/jxgh/jxboot-helmfile-resources/defaults.yaml
Labels: size/XS, approved

#3058 feat: update tekton charts
  charts/cdf/tekton-pipeline/defaults.yaml
Labels: size/XS, approved

#3063 chore: upgrade cert manager to 1.6.3
  charts/jetstack/cert-manager/defaults.yaml
Labels: size/XS, approved, ok-to-test

#3064 chore: delete gcp sa after tests are done
  .lighthouse/jenkins-x/bdd/gsm/ci.sh
  .lighthouse/jenkins-x/bdd/terraform-ci.sh
  .lighthouse/jenkins-x/bdd/terraform.yaml.gotmpl
Labels: size/S, approved
