Repository jenkins-x/jx3-versions, pull requests merged in 2023-11, with the labels that each got.

#3806 feat: upgrade Loki charts
  charts/grafana/loki/defaults.yaml
  charts/grafana/loki/values.yaml
Labels: approved, size/M, ok-to-test

#3807 feat: upgrade promtail helm v6.15.3
  charts/grafana/promtail/defaults.yaml
Labels: size/XS, approved, ok-to-test

#3817 chore: upgrade jx-acme
  charts/jxgh/acme-jx/defaults.yaml
Labels: size/XS, approved, lgtm, ok-to-test
