Repository jenkins-x/jx3-versions, pull requests merged in 2024-10, with the labels that each got.

#3952 fix: mark jx release as latest
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/release/promote-vs.sh
Labels: size/S, approved

#3947 feat: script to filter helmfile selector by release name
  src/get-selectors-by-release-and-clean.sh
Labels: size/L, approved, ok-to-test

#3958 fix: schema problem with cert-manager
  charts/jetstack/cert-manager/defaults.yaml
Labels: size/XS, approved

#3959 chore: remove unused value
  charts/jxgh/lighthouse/values.yaml.gotmpl
Labels: size/XS, approved

#3962 fix: make jx gitops kpt update not add update too much
  .lighthouse/jenkins-x/release/promote-vs.sh
Labels: size/S, approved

#3977 fix: terraform repos get previous version
  .lighthouse/jenkins-x/release/promote-vs.sh
Labels: size/XS, approved

#3968 fix: replace broken helm repository and upgrade bank-vault
  charts/bank-vaults/vault-operator/defaults.yaml
  charts/banzaicloud-stable/vault-operator/defaults.yaml
  charts/repositories.yml
Labels: size/S, approved
