Repository jenkins-x/jx3-versions, pull requests merged in 2025-01, with the labels that each got.

#4024 chore: Add missing prefix for ingress-nginx and fix gitUrl
  charts/ingress-nginx/ingress-nginx/defaults.yaml
  charts/repositories.yml
Labels: size/XS, approved, ok-to-test

#2831 fix: do not push empty commits
  .lighthouse/jenkins-x/release/promote-jx-website.sh
Labels: size/XS, approved, ok-to-test

#4034 fix: move from stable
  charts/repositories.yml
  charts/stable/docker-registry/defaults.yaml
  charts/stable/external-dns/defaults.yaml
  charts/twuni/docker-registry/secret-schema.yaml
  charts/twuni/docker-registry/values.yaml.gotmpl
Labels: size/XS, approved

#4033 chore: remove unused chart velero
  charts/stable/velero/defaults.yaml
  charts/stable/velero/values.yaml.gotmpl
Labels: approved, size/M
